### ISSUE TITLE
[QUESTION] How to call build method before editor loads?

### ISSUE THREAD

**Issue by devwax** [chili-publish/publisher-interface#10]
From the README...
> The PublisherConnector `build` method must be called before the IFrame loads the Editor.

This part I'm not clear on. [The example in the readme](https://github.com/chili-publish/publisher-connector#%EF%B8%8F-important-) shows an iframe with a `src` attribute containing a valid editor URL. This should cause the editor in the iframe to load _before_ the `build` method fires, right? Unless I'm missing something...

I'm attempting to implement it in React with a ref to the iframe, but can't get it to load the editor. Tried withholding the src URL, setting it later, etc, to no avail. When I set the editor iframe src URL I get a blank editor screen and the error:
> "Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'localhost' is not a suffix of ************.chili-publish-sandbox.online'."

Any ideas would be great. Thanks.

**Comment by sean-at-chili** [comment]
> src attribute containing a valid editor URL. This should cause the editor in the iframe to load before the build method fires, right?

I need to update the documentation to be clearer, so the order of events must be:
- `src` is set
- `build` is called
- iframe loads

You don't want to use `onload` or put `build` in a timeout. I will update the documentation to be clearer about the intention.

I threw a very simple React example using ref: 
https://codesandbox.io/s/epic-wu-mx6n5b?file=/src/Publisher.js

I have not tested it on every use cases, but that should be the general way to go.

<br/>

> "Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'localhost' is not a suffix of ************.chili-publish-sandbox.online'."

Can you reproduce the error in codesandbox or similar and send me an example? You can use my document URL for testing (as the key is safe to be leaked to the public) 

https://ft-nostress.chili-publish.online/ft-nostress/editor_html.aspx?doc=d7f6c3fd-bd09-4569-a197-91bca4c6626c&apiKey=XqJpQ7mEcgexARnf55Vwyzx0SmbML6jBSjUDAjHY_DCV2YuM7t14Q8b2nk_7r3+i6xKXfT4Is5QRMuqJEAS8oFlP2nE5rjHU5cRgpGqckFY=

**Comment by seancrowe** [comment]
> src attribute containing a valid editor URL. This should cause the editor in the iframe to load before the build method fires, right?

I need to update the documentation to be clearer, so the order of events must be:
- `src` is set
- `build` is called
- iframe loads

You don't want to use `onload` or put `build` in a timeout. I will update the documentation to be clearer about the intention.

I threw a very simple React example using ref: 
https://codesandbox.io/s/epic-wu-mx6n5b?file=/src/Publisher.js

I have not tested it on every use cases, but that should be the general way to go.

<br/>

> "Uncaught DOMException: Failed to set the 'domain' property on 'Document': 'localhost' is not a suffix of ************.chili-publish-sandbox.online'."

Can you reproduce the error in codesandbox or similar and send me an example? You can use my document URL for testing (as the key is safe to be leaked to the public) 

https://ft-nostress.chili-publish.online/ft-nostress/editor_html.aspx?doc=d7f6c3fd-bd09-4569-a197-91bca4c6626c&apiKey=XqJpQ7mEcgexARnf55Vwyzx0SmbML6jBSjUDAjHY_DCV2YuM7t14Q8b2nk_7r3+i6xKXfT4Is5QRMuqJEAS8oFlP2nE5rjHU5cRgpGqckFY=

**Comment by devwax** [comment]
Thanks for the example. That should be enough to get me on track. I'll try that and post again if I'm still having problems.

My existing attempt is something like this:

```javascript
export default function Editor({ editorUrl }) {
    const [editorUrlLive, setEditorUrlLive] = useState('')
    const chiliEditorIframe = useRef(null)

    useEffect(() => {
        if (chiliEditorIframe.current) {
                setEditorUrlLive(editorUrl)
                PublisherConnector.build(chiliEditorIframe.current).then(
                    (publisherConnector) => {
                        setEditorUrlLive(editorUrl)
                        publisherConnector.alert("Hi!")
                    }
                )
        }

    }, [editorUrl])

    return (<div id="chili-editor" className="h-[90%] mb-5 border-l flex flex-col justify-center items-center">        
        <iframe
            id="chili-iframe"
            ref={chiliEditorIframe}
            src={editorUrlLive}
            title="chili-iframe-title"
            style={{ width: '100%', height: '500px' }}
        ></iframe>
    </div>)
})
```

**Comment by seancrowe** [comment]
As of 1.0.0 there is a built-in method call `buildOnElement()`, see the [README.md](https://github.com/chili-publish/publisher-interface/blob/main/README.md) for more information
