### ISSUE TITLE
Get all variables associated with a frame.

### ISSUE THREAD

**Issue by danielkjcoles** [chili-publish/publisher-interface#35]
Bit of a long shot, but I was wondering if there was any functionality that would get all the variables associated with a particular frame?

A bit of context. I have a text frame that contains three short text variables, a long text variable and a list variable. On selecting that text frame I want to get the objects for these five variables. So I can then display custom input fields for these five variables etc.

I'm able to get one of the five variables by setting the variable in the text frame's "Frame Link Settings" in the Chili BackOffice and using the following:

```
await publisher.addListener("SelectedFrameChanged", async target => {
     const variable = await publisher.getObject('document.selectedFrame.linkSettings.variable');
});
```
But this is obviously only one of the five.

I'm also aware that I can get all of the variables in the document by using the following:

`await publisher.getObject("document.variables");`

and then loop through etc as in the Chili Publisher documentation. But I just want the five variables associated with this frame.

I've had a look through the Chili Publisher docs, but I was curious if anything like the following exists:

```
await publisher.addListener("SelectedFrameChanged", async target => {
     const variables = await publisher.executeFunction("document.selectedFrame","GetVariables");
});
```

Or if there is any other way to possibly achieve this functionality? Or if I'm going about it in the complete wrong way.

Any help at all would be appreciated.

Cheers

**Comment by danielkjcoles** [comment]
You're probably right, but thanks for the suggestion I'll give it a shot

**Comment by seancrowe** [comment]
I am way late to the party, but no there is no way I know of to get all variables in a text frame natively in CHILI

The private data as suggested is a good workaround. Another option is to parse the textflow of a frame for all the variables. You can get the textflow from: ```await publisher.getObject('document.selectedFrame').textFlow```
