### ISSUE TITLE
[QUESTION] Cross-origin iframe blockage issue

### ISSUE THREAD

**Issue by aarongerig** [chili-publish/publisher-interface#54]
**What do you want to ask us?**
When integrating `PublisherInterface` on my website (localhost), I get the following error message in the console:

```log
EXTERNAL ERROR: Failed to read a named property 'OnGetApiKey' from 'Window': Blocked a frame with origin "https://my-environment.chili-publish-sandbox.online" from accessing a cross-origin frame.
```

The much bigger issue though is, that I cannot access the returned `PublisherInterface` instance, as the promise never gets properly resolved. My code looks like this:

```js
(async () => {
    const editorDiv = document.getElementById("editor-div");
    const publisher = await PublisherInterface.buildOnElement(editorDiv, "https://my-environment.chili-publish- sandbox.online/my-environment/editor_html.aspx?doc=<document_id>&apiKey=<api_key>");
    console.log(publisher); // <-- this is never run
})();
```

Is there something I need to configure to make this work?

**Comment by aarongerig** [comment]
So my actual implementation looks a bit different to what I posted above. I reduced the code snippet to the relevant parts only. In the following I will try to describe the entire implementation of the PublisherInterface.

I installed the library with yarn by running `yarn add @chili-publish/publisher-interface` (we're using Webpack to bundle our Javascript). The javascript file/component looks like this:

```js
import { $ } from 'uikit/src/js/util';
import { PublisherInterface } from '@chili-publish/publisher-interface';

export default {
  props: {
    editorUrl: String, // Here we retrieve the editor URL as a prop from the HTML
  },

  computed: {
    editor() {
      return $('#editor', this.$el); // This returns the element for the editor iFrame
    },
  },

  async connected() {
    console.log('Hello there! 👋');
    this.publisher = await PublisherInterface.buildOnElement(this.editor, this.editorUrl);
    /* From here on, nothing is run... */
    console.log('Publisher initialized! 🥳', this.publisher);
    const documentName = await this.publisher.getObject('document.name');
    console.log(documentName);
  },
};
```

This is a special component that attaches to a certain DOM element. This works (I confirmed that) perfectly on many other occasions. The first `console.log()` is logged in the console, then the PublisherInterface is instantiated, but after that, nothing else gets run in my code (see attached screenshot).

<img width="1560" alt="Bildschirmfoto 2023-12-18 um 13 38 40" src="https://github.com/chili-publish/publisher-interface/assets/17384333/162a0cdb-f94d-41d9-a298-276421f7943d">

**Comment by seancrowe** [comment]
The message below is always present if you load in an iframe. To be honest, it shouldn't say "ERROR", because it is not really an error.

> EXTERNAL ERROR: Failed to read a named property 'OnGetApiKey' from 'Window': Blocked a frame with origin "https://my-environment.chili-publish-sandbox.online" from accessing a cross-origin frame.

If the await never returns, it means the handshake between the library and the iframe did not go through. Add the {debug: true} to see the logging of the handshake to confirm if it does or does not go through. See [debugging](https://github.com/chili-publish/publisher-interface?tab=readme-ov-file#debugging)

You almost got the whole project there, if you send that entire Vue page (I think it is Vue), so I can run locally if I provide my own editorURL, I can test it out really quick. I could probably build something off the images you posted, but I think it is better for you to provide the example.

Sean

**Comment by aarongerig** [comment]
@seancrowe Thanks for your answer. I'll try to create an example repo for you to reproduce the issue and post it here once ready.

**Comment by aarongerig** [comment]
@seancrowe Found the issue! I was using a proxy method within my own application to redirect to the CHILI editor url. It looked like this: `https://localhost/chili/editor-proxy/<environment>/editor_html.aspx?...`. Because of that, the handshake between lib and iframe could not work (non-matching domains). I removed the proxy method now and it works flawlessly.

Thanks for the tips!
